version: '3.3'
services:
 os:
  image: "minio/minio"
  ports:
   - "9000:9000"
   - "9001:9001"
  volumes:
   - os:/data
  command: server /data --console-address :9001
  environment:
   MINIO_ACCESS_KEY: wonderfuljohnson
   MINIO_SECRET_KEY: hamster1234

volumes:
 os:
